import fs from 'fs';
const src = fs.readFileSync(new URL('../js/app.js', import.meta.url), 'utf8');
const i = src.indexOf('function cashFlow'), j = src.indexOf('const sumBy');
const code = src.slice(i, j);
let entries = [];
const store = { view: () => ({ months: ['2026-09', '2026-10'], by: { '2026-09': { entries: entries.filter((e) => e.m === 9) }, '2026-10': { entries: entries.filter((e) => e.m === 10) } } }) };
const fns = new Function('store', code + '; return { cashFlow, cashLeft, cashStartFor };')(store);
const ok = (c, m) => { console.log((c ? 'ok  : ' : 'FAIL: ') + m); if (!c) process.exitCode = 1; };
const cash = { name: 'Cash', type: 'cash', limit: 0 };
entries = [{ m: 9, account: 'Cash', type: 'Expense', amount: 200 }, { m: 10, account: 'Cash', type: 'Expense', amount: 150 }, { m: 10, account: 'Credit Card', type: 'Expense', amount: 999 }];
ok(fns.cashLeft(cash) === null, 'no cash amount set -> nothing to show');
cash.limit = fns.cashStartFor(cash, 1000);
ok(fns.cashLeft(cash) === 1000, 'setting "1000 on me now" shows exactly 1000 right away (past cash spending is accounted for)');
entries.push({ m: 10, account: 'Cash', type: 'Expense', amount: 85.5 });
ok(fns.cashLeft(cash) === 914.5, 'a new cash expense of 85.50 counts it down to 914.50');
ok(fns.cashLeft(cash) !== 1000 - 999, 'card spending does not touch cash');
entries.push({ m: 10, account: 'Cash', type: 'Income', amount: 100 });
ok(fns.cashLeft(cash) === 1014.5, 'cash received adds back');
cash.limit = fns.cashStartFor(cash, 500);
ok(fns.cashLeft(cash) === 500, 're-entering the amount later resets what is on hand to that number');
if (!process.exitCode) console.log('\nall passed');
